version: 2.1
jobs:
  post_leaves_to_slack:
    docker:
      - image: ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Post Leaves To Slack
          command: |
            gem install bundler -v 2.3.4
            bundle install
            ./exe/jiva_hr_tools post_leaves_to_slack

workflows:
  daily:
    triggers:
      - schedule:
          cron: "45 09 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - post_leaves_to_slack
